.TH gnome-panel 1 2006\-03\-07
.SH NAME
gnome-panel \- display the GNOME panel
.SH SYNOPSIS
\fBgnome-panel\fR
.SH "DESCRIPTION"
The GNOME panel displays an area on your screen, which acts as a
repository for the main menu, application launchers, and applets.
.SH "OPTIONS"
The GNOME panel obeys all normal GNOME and GTK+ command line options,
and has no application specific options.
.SH "SEE ALSO"
\fBgnome-options\fR(7),
\fBgtk-options\fR(7).
