/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Panel Settings");
gchar *s = N_("_Enable tooltips");
gchar *s = N_("Close _drawer if a launcher inside it is pressed");
gchar *s = N_("_Raise panels on mouse-over");
gchar *s = N_("_Confirm the removal of panels with a dialog");
gchar *s = N_("_Try to avoid overlapping panels");
gchar *s = N_("General");
gchar *s = N_("_Enable animation");
gchar *s = N_("Animation speed");
gchar *s = N_("Slow");
gchar *s = N_("Medium");
gchar *s = N_("Fast");
gchar *s = N_("Animation delay");
gchar *s = N_("Hide delay (ms)");
gchar *s = N_("Show delay (ms)");
gchar *s = N_("Animattion");
gchar *s = N_("Meun options");
gchar *s = N_("_Keep menus in memory");
gchar *s = N_("_Use large icons");
gchar *s = N_("Global Menu");
gchar *s = N_("In the menu");
gchar *s = N_("In the menu");
gchar *s = N_("In the menu");
gchar *s = N_("In the menu");
gchar *s = N_("In the menu");
gchar *s = N_("In the menu");
gchar *s = N_("In a submenu");
gchar *s = N_("In a submenu");
gchar *s = N_("In a submenu");
gchar *s = N_("In a submenu");
gchar *s = N_("In a submenu");
gchar *s = N_("In a submenu");
gchar *s = N_("Off");
gchar *s = N_("Off");
gchar *s = N_("Off");
gchar *s = N_("Off");
gchar *s = N_("Off");
gchar *s = N_("Off");
gchar *s = N_("Programs");
gchar *s = N_("Favourites");
gchar *s = N_("Applets");
gchar *s = N_("Distribution");
gchar *s = N_("KDE");
gchar *s = N_("Panel");
gchar *s = N_("Desktop");
gchar *s = N_("In the menu");
gchar *s = N_("In a submenu");
gchar *s = N_("Off");
gchar *s = N_("Menus");
