/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Panel Settings");
gchar *s = N_("_Close drawer if a launcher inside it is pressed");
gchar *s = N_("_Raise panels on mouse-over");
gchar *s = N_("Keep panels below other windows");
gchar *s = N_("Keep panels on same level as other windows");
gchar *s = N_("Keep panels above other windows");
gchar *s = N_("Automatically re-check menus for newly installed software");
gchar *s = N_("General");
gchar *s = N_("_Enable animation");
gchar *s = N_("Animation speed:");
gchar *s = N_("Fast");
gchar *s = N_("Medium");
gchar *s = N_("Slow");
gchar *s = N_("Hide delay (ms):");
gchar *s = N_("Show delay (ms):");
gchar *s = N_("Animation");
gchar *s = N_("_Enable key bindings");
gchar *s = N_("Grab key...");
gchar *s = N_("Grab key...");
gchar *s = N_("Mod1-F1");
gchar *s = N_("Menu");
gchar *s = N_("Control-Mod1-m");
gchar *s = N_("Disabled");
gchar *s = N_("Mod1-F1");
gchar *s = N_("Mod1-F2");
gchar *s = N_("Control-Mod1-r");
gchar *s = N_("Menu");
gchar *s = N_("Disabled");
gchar *s = N_("Mod1-F2");
gchar *s = N_("Popup menu key:");
gchar *s = N_("Run dialog key:");
gchar *s = N_("Key bindings");
