/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Screenshot");
gchar *s = N_("Preview");
gchar *s = N_("Options");
gchar *s = N_("_Save screenshot to file:");
gchar *s = N_("Save screenshot to _desktop");
gchar *s = N_("Save screenshot to _web page (save in ~/public__html)");
gchar *s = N_("_Print screenshot...");
