/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Panel Settings");
gchar *s = N_("_Close drawer if a launcher inside it is pressed");
gchar *s = N_("_Raise panels on mouse-over");
gchar *s = N_("Confirm the removal of panels with a _dialog");
gchar *s = N_("_Try to avoid overlapping panels");
gchar *s = N_("_Keep menus in memory");
gchar *s = N_("General");
gchar *s = N_("_Enable animation");
gchar *s = N_("Animation speed");
gchar *s = N_("Fast");
gchar *s = N_("Medium");
gchar *s = N_("Slow");
gchar *s = N_("Hide delay (ms)");
gchar *s = N_("Show delay (ms)");
gchar *s = N_("Animation");
