/* Generated by GOB (v0.93.0) on Mon Mar 20 16:26:09 2000
   (do not edit directly) */

#define GOB_VERSION_MAJOR 0
#define GOB_VERSION_MINOR 93
#define GOB_VERSION_PATCHLEVEL 0

#include "title-item.h"

/* utility types we may need */
typedef struct { gpointer a; gpointer b; } ___twopointertype;
typedef struct { gpointer a; gpointer b; gpointer c; } ___threepointertype;

/* self casting macros */
#define SELF(x) TITLE_ITEM(x)
#define IS_SELF(x) IS_TITLE_ITEM(x)
#define SELF_CLASS(x) TITLE_ITEM_CLASS(x)

/* here are local prototypes */
static void title_item_init (TitleItem *o) G_GNUC_UNUSED;
static void title_item_class_init (TitleItemClass *c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkMenuItemClass *parent_class = NULL;

guint
title_item_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"TitleItem",
			sizeof (TitleItem),
			sizeof (TitleItemClass),
			(GtkClassInitFunc) title_item_class_init,
			(GtkObjectInitFunc) title_item_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (gtk_menu_item_get_type(), &info);
	}

	return type;
}


#ifdef __GNUC__
static const typeof(&title_item_new) new __attribute__ ((__unused__)) = title_item_new;
#define new(args...) title_item_new(##args)
#else /* __GNUC__ */
static GtkWidget *(* new) (void) = title_item_new;
#endif /* __GNUC__ */

/* a macro for creating a new object of our type */
#define GET_NEW ((TitleItem *)gtk_type_new(title_item_get_type()))

static void 
title_item_init (TitleItem *o)
{
return;
}
static void 
title_item_class_init (TitleItemClass *c)
{
	GtkItemClass *gtk_item_class = (GtkItemClass *)c;

	parent_class = gtk_type_class (gtk_menu_item_get_type ());

	gtk_item_class->select = NULL;
return;
}




#line 5 "title-item.gob"
GtkWidget *
title_item_new (void)
{
#line 84 "title-item.c"
{
#line 7 "title-item.gob"
	
		return GTK_WIDGET(GET_NEW);
	}}
#line 90 "title-item.c"


#ifndef __GNUC__
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___title_item_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
	___title_item_really_bad_hack_to_avoid_warnings();
}
#endif /* __GNUC__ */

