/* Generated by GOB (v0.93.0)   (do not edit directly) */

#include <gtk/gtk.h>

#ifndef __TITLE_ITEM_H__
#define __TITLE_ITEM_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define TYPE_TITLE_ITEM	(title_item_get_type())
#define TITLE_ITEM(obj)	GTK_CHECK_CAST((obj),title_item_get_type(),TitleItem)
#define TITLE_ITEM_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass),title_item_get_type(),TitleItemClass)
#define IS_TITLE_ITEM(obj)	GTK_CHECK_TYPE((obj), title_item_get_type ())


/*
 * Main object structure
 */
#ifndef __TYPEDEF_TITLE_ITEM__
#define __TYPEDEF_TITLE_ITEM__
typedef struct _TitleItem TitleItem;
#endif
struct _TitleItem {
	GtkMenuItem __parent__;
};

/*
 * Class definition
 */
typedef struct _TitleItemClass TitleItemClass;
struct _TitleItemClass {
	GtkMenuItemClass __parent__;
};


/*
 * Public methods
 */
guint	title_item_get_type	(void);
GtkWidget *	title_item_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif