/* Generated by GOB (v1.0.4)   (do not edit directly) */

#include <gtk/gtk.h>

#ifndef __TITLE_ITEM_H__
#define __TITLE_ITEM_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define TYPE_TITLE_ITEM	(title_item_get_type())
#define TITLE_ITEM(obj)	GTK_CHECK_CAST((obj), title_item_get_type(), TitleItem)
#define TITLE_ITEM_CONST(obj)	GTK_CHECK_CAST((obj), title_item_get_type(), TitleItem const)
#define TITLE_ITEM_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass), title_item_get_type(), TitleItemClass)
#define IS_TITLE_ITEM(obj)	GTK_CHECK_TYPE((obj), title_item_get_type ())

#ifdef GTK_CHECK_GET_CLASS
#define TITLE_ITEM_GET_CLASS(obj)	GTK_CHECK_GET_CLASS((obj), title_item_get_type(), TitleItemClass)
#else /* !GTK_CHECK_GET_CLASS */
#define TITLE_ITEM_GET_CLASS(obj)	((TitleItemClass *)GTK_OBJECT(obj)->klass)
#endif /* GTK_CHECK_GET_CLASS */

/*
 * Main object structure
 */
#ifndef __TYPEDEF_TITLE_ITEM__
#define __TYPEDEF_TITLE_ITEM__
typedef struct _TitleItem TitleItem;
#endif
struct _TitleItem {
	GtkMenuItem __parent__;
};

/*
 * Class definition
 */
typedef struct _TitleItemClass TitleItemClass;
struct _TitleItemClass {
	GtkMenuItemClass __parent__;
};


/*
 * Public methods
 */
guint	title_item_get_type	(void) G_GNUC_CONST;
GtkWidget * 	title_item_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
