/* Generated by GOB (v1.0.4)   (do not edit directly) */

#ifndef __TITLE_ITEM_PRIVATE_H__
#define __TITLE_ITEM_PRIVATE_H__

#include "title-item.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
