/* -*- Mode: C; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 8 -*- */
module GNOME {
	interface caplet {
                void try();
                void revert();
                void ok ();
                void cancel ();
                void help ();
	};
	interface control_center {
		/* requests an ID on the panel */
                void state_saved (in long id);
                void state_changed (in long id);
	};
};

