/* -*- Mode: C; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 8 -*- */
module GNOME {
	interface control_panel {
		/* requests an ID on the panel */
		short cpo_request_id(in string cookie);
		void cpo_register(in string ior,
				     in short cpo_id);
		void quit (in string cookie);
	};
        /* functions for the control-panel to call on the objects */
	interface control_panel_object {
	};
};

