/**
 * gnome-ditem.idl: GNOME Desktop Item types
 *
 * Copyright (C) 2001  SuSE Linux AG.
 *
 * Authors:
 *   Martin Baulig <baulig@suse.de>
 */

#ifndef GNOME_DITEM_IDL
#define GNOME_DITEM_IDL

#include <Bonobo.idl>
#include <Gnome.idl>

module GNOME {

    module Desktop {

	typedef Bonobo::PropertySet ExtraAttributes;

	enum Encoding {
	    ENCODING_NONE,
	    ENCODING_UNKNOWN,
	    ENCODING_UTF8,
	    ENCODING_LEGACY_MIXED
	};

	enum EntryType {
	    ENTRY_TYPE_UNKNOWN,
	    ENTRY_TYPE_APPLICATION,
	    ENTRY_TYPE_URL,
	    ENTRY_TYPE_LINK,
	    ENTRY_TYPE_FSDEVICE,
	    ENTRY_TYPE_MIMETYPE,
	    ENTRY_TYPE_DIRECTORY,
	    ENTRY_TYPE_SERVICE,
	    ENTRY_TYPE_SERVICETYPE,
	    ENTRY_TYPE_PANEL_APPLET,
	    ENTRY_TYPE_SEPARATOR
	};

	struct Entry {
	    LocalizedStringList Name;
	    LocalizedStringList Comment;
	    string Icon;
	    string Exec;
	    string TryExec;
	    string URL;
	    stringlist SortOrder;
	    ExtraAttributes Attributes;
	    EntryType Type;
	    boolean Terminal;
	};

    };
};

#endif
