/**
 * gnome-ditem.idl: GNOME Desktop Item types
 *
 * Copyright (C) 2001  SuSE Linux AG.
 *
 * Authors:
 *   Martin Baulig <baulig@suse.de>
 */

#ifndef GNOME_DITEM_IDL
#define GNOME_DITEM_IDL

#include <Bonobo.idl>

module GNOME {

    struct LocalizedString {
	string locale;
	string text;
    };

    typedef sequence<LocalizedString> LocalizedStringList;

    typedef Bonobo::PropertySet ExtraAttributes;

    enum DesktopEntryType {
	DESKTOP_ENTRY_TYPE_UNKNOWN,
	DESKTOP_ENTRY_TYPE_APPLICATION,
	DESKTOP_ENTRY_TYPE_URL,
	DESKTOP_ENTRY_TYPE_LINK,
	DESKTOP_ENTRY_TYPE_FSDEVICE,
	DESKTOP_ENTRY_TYPE_MIMETYPE,
	DESKTOP_ENTRY_TYPE_DIRECTORY,
	DESKTOP_ENTRY_TYPE_SERVICE,
	DESKTOP_ENTRY_TYPE_SERVICETYPE 
    };

    struct DesktopEntry {
	LocalizedStringList Name;
	LocalizedStringList Comment;
	string Icon;
	string Exec;
	string TryExec;
	string URL;
	stringlist SortOrder;
	ExtraAttributes Attributes;
	DesktopEntryType Type;
	boolean Terminal;
    };

};

#endif
