/*
 * The cookie is an extremely *BAD* hack that we have implemented
 * for security reasons for *NOW*
 */
module GNOME {
	interface Panel {
		/* requests an ID on the panel */
		short applet_request_id(in string cookie,
					in string path,
					in string param,
					in short dorestart,
					out string cfgpath,
					out string globcfgpath,
					out unsigned long wid);

		/* Sends the object identifier for the Applet server that
		   contacts the Panel */
		void applet_register(in string cookie, in string ior,
				     in short applet_id);

		void applet_abort_id(in string cookie, in short applet_id);
		void applet_request_glob_cfg(in string cookie,
					     out string globcfgpath);
		void applet_remove_from_panel (in string cookie,
					       in short applet_id);
		short applet_get_panel (in string cookie, in short applet_id);
		short applet_get_pos (in string cookie, in short applet_id);
		short applet_get_panel_orient (in string cookie,
					       in short applet_id);
		void applet_show_menu (in string cookie, in short applet_id);
		void applet_drag_start (in string cookie, in short applet_id);
		void applet_drag_stop (in string cookie, in short applet_id);
		void applet_add_callback (in string cookie, 
					  in short applet_id,
					  in string callback_name,
					  in string menuitem_text);
		void applet_add_tooltip (in string cookie, in short applet_id,
					 in string tooltip);
		void applet_remove_tooltip (in string cookie,
					    in short applet_id);
		short applet_in_drag (in string cookie);
		void quit(in string cookie);
	};

	interface Applet {
		void change_orient (in string cookie,
				    in short applet_id,
				    in short orient);
		void do_callback (in string cookie,
				  in short applet_id,
				  in string callback_name);
		short session_save (in string cookie,
				    in short applet_id,
				    in string cfgpath,
				    in string globcfgpath);

		/* params is only used if the applet process handeles more
		   applet types */
		void start_new_applet (in string cookie, in string param);
	};
};

