module GNOME {
	interface Panel {
		/* requests an ID on the panel */
		short applet_request_id(in string goad_id,
					out string cfgpath,
					out string globcfgpath,
					out unsigned long wid);
		
		/* Sends the object identifier for the Applet server that
		   contacts the Panel, goad_ids is a comma separated list
		   of the goad_id's this applet can handle, this call also
		   serves as basically a signal for the panel to start
		   a new applet, since it tries to start extern applets
		   synchroniously to make it faster on X and make
		   multiapplets possible */
		void applet_register(in Object obj,
				     in short applet_id,
				     in string goad_id,
				     in string goad_ids);

		/*abort the applet load (before we register)*/
		void applet_abort_id(in short applet_id);

		void applet_request_glob_cfg(out string globcfgpath);
		void applet_remove_from_panel(in short applet_id);
		short applet_get_panel (in short applet_id);
		short applet_get_pos (in short applet_id);
		short applet_get_panel_orient (in short applet_id);
		void applet_show_menu (in short applet_id);
		void applet_drag_start (in short applet_id);
		void applet_drag_stop (in short applet_id);
		void applet_add_callback (in short applet_id,
					  in string callback_name,
					  in string stock_item,
					  in string menuitem_text);
		void applet_remove_callback (in short applet_id,
					     in string callback_name);
		void applet_add_tooltip (in short applet_id,
					 in string tooltip);
		void applet_remove_tooltip (in short applet_id);
		short applet_in_drag ();
		void sync_config (in short applet_id);
		void quit ();
	};

	interface Applet {
		void change_orient (in short applet_id,
				    in short orient);
		void do_callback (in short applet_id,
				  in string callback_name);
		short session_save (in short applet_id,
				    in string cfgpath,
				    in string globcfgpath);
		/* start new applet of goad_id type */
		void start_new_applet (in string goad_id);
		void back_change (in short applet_id,
				  in short back_type,
				  in string pixmap,
				  in short c_red,
				  in short c_green,
				  in short c_blue);
		void tooltips_state (in short applet_id,
				     in short enabled);
	};
};

