
#include <gnome-factory.idl>

module GNOME {
	module Terminal {
		interface Terminal {
		};

		interface TerminalFactory : GenericFactory {
			Terminal create_terminal (in string geometry);
		};
	};
};
